export enum RootRoutes {
    AUTHENTICATION = 'AUTHENTICATION',
    APP = 'APP',
}

export enum AuthenticationRoutes {
    // SCREENS
    LOGIN_SCREEN = 'LOGIN_SCREEN',
}

export enum AppRoutes {
    TABS = 'TABS',
    HOME_SCREEN = 'HOME_SCREEN',
    ACCOUNT_SCREEN = 'ACCOUNT_SCREEN',
    EXERCISES_SCREEN = 'EXERCISES_SCREEN',
    WORKOUTS_SCREEN = 'WORKOUTS_SCREEN',

    // STACKS

    HOME_STACK = 'HOME_STACK',
    ACCOUNT_STACK = 'ACCOUNT_STACK',
    EXERCISES_STACK = 'EXERCISES_STACK',
    WORKOUTS_STACK = 'WORKOUTS_STACK',

    // SCREENS

    EXERCISE_DETAIL_SCREEN = 'EXERCISE_DETAIL_SCREEN',
    EXERCISES_SELECTION_SCREEN = 'EXERCISES_SELECTION_SCREEN',

    WORKOUT_DETAIL_SCREEN = 'WORKOUT_DETAIL_SCREEN',
    WORKOUT_CREATION_SCREEN = 'WORKOUT_CREATION_SCREEN',
    WORKOUT_SESSION_CREATION_SCREEN = 'WORKOUT_SESSION_CREATION_SCREEN',
    WORKOUT_SESSION_DETAILS = 'WORKOUT_SESSION_DETAILS',
    WORKOUT_SESSION_EDIT = 'WORKOUT_SESSION_EDIT',
    WORKOUT_SELECTION_SCREEN = 'WORKOUT_SELECTION_SCREEN',
    WORKOUT_EDIT_SCREEN = 'WORKOUT_EDIT_SCREEN',

    // Other
    PROFILE_SCREEN = 'PROFILE_SCREEN',
}
